# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


#pod 'DTCoreText', '~> 1.6.11'

#pod 'CocoaHTTPServer'
#pod 'VKFoundation', '~> 0.1.2'
pod 'CocoaHTTPServer', '~> 2.3'
pod 'DTCoreText', '~> 1.6.17'
#pod 'AFNetworking', '1.3.3'
 pod 'AFNetworking', '~> 3.0.4'
pod 'CocoaLumberjack', '~> 1.7.0'
pod 'VKFoundation', '0.1.1'



target 'VKVideoPlayerPro' do
end

target 'VKVideoPlayerProTests' do
end

target 'VKVideoPlayerProUITests' do
end

